### ISSUE TITLE
Remove change address generation

### ISSUE THREAD

**Issue by MeshCollider** [Omnicoin-Project/Omnicoin#23]
We should remove the generation of new addresses for change and instead use the address used to send the coins, because change addresses are a safety risk (the private keys are not backed up)

**Comment by caffeinewriter** [comment]
At the very least, we should include them in the backup by default, or by default, send change back to the same address.

**Comment by DoctorBlue** [comment]
Could we add a checkbox or mechanism of some sort that makes this behaviour optional?

**Comment by caffeinewriter** [comment]
:+1:
