### ISSUE TITLE
./OmniCoind: error while loading shared libraries: libminiupnpc.so.10 but it's installed

### ISSUE THREAD

**Issue by BurntRouter** [Omnicoin-Project/Omnicoin#29]
So I have all the deps installed. Here's what I get when I ldd OmniCoind
root@RoutersAdventures:~# ldd OmniCoind
./OmniCoind: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20'
not found (required by ./OmniCoind)
        linux-vdso.so.1 =>  (0x00007fffd11fe000)
        libboost_system.so.1.55.0 => /usr/lib/x86_64-linux-gnu/libboost_system.s
o.1.55.0 (0x00007fec83e9a000)
        libboost_filesystem.so.1.55.0 => /usr/lib/x86_64-linux-gnu/libboost_file
system.so.1.55.0 (0x00007fec83c84000)
        libboost_program_options.so.1.55.0 => /usr/lib/x86_64-linux-gnu/libboost
_program_options.so.1.55.0 (0x00007fec83a15000)
        libboost_thread.so.1.55.0 => /usr/lib/x86_64-linux-gnu/libboost_thread.s
o.1.55.0 (0x00007fec837fe000)
        libdb_cxx-5.3.so => /usr/lib/x86_64-linux-gnu/libdb_cxx-5.3.so (0x00007f
ec83439000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fec831d
9000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f
ec82dfe000)
        libminiupnpc.so.10 => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fec82bd
f000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fec82
8db000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fec825d5000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fec823be000
)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fec81ff9000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fec81df1000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fec81bec000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fec840ab000)

**Comment by DoctorBlue** [comment]
Did you install libminiupnpc-dev or just libminiupnpc5? You need the developer package.

**Comment by BurntRouter** [comment]
I did libminiupnpc-dev 
"libminiupnpc-dev is already the newest version."

**Comment by DoctorBlue** [comment]
I presume that you are also using the makefile for compiling?

**Comment by BurntRouter** [comment]
Correct

**Comment by BurntRouter** [comment]
Could it be I'm compiling on a desktop then transferring it to server?

**Comment by BurntRouter** [comment]
Figured it out. The command was installing libminiupnpc.so.8
I renamed it to libminiupnpc.so.10
