### ISSUE TITLE
Error initializing wallet database environment

### ISSUE THREAD

**Issue by Xefrok** [Omnicoin-Project/Omnicoin#30]
I compiled OmniCoin Wallet in Ubuntu, everything ok but when i tried to run OmniCoind get me this error.

Error initializing wallet database environment

**Comment by DoctorBlue** [comment]
It might be related to problems with permissions in the directory where it tries to write the database files. 

Regardless, Omni coin has been dead for quite a while, so I doubt there is much tog gain from installing it ☺️
